### ISSUE TITLE
兄弟，我视频是h265的无法播放，求助

### ISSUE THREAD

**Issue by RideShi** [alexLiu-cn/H265VideoDemo#1]

**Comment by YYHNobug** [comment]
兄弟，h265不能播的解决了没

**Comment by RideShi** [comment]
使用FFMpeg转格式 已经OK了

**Comment by YYHNobug** [comment]
转成什么格式的了？我用AVPlayer播放h265的, 有声音没画面

**Comment by RideShi** [comment]
转mp4 你可能语法写的不对吧 我之前也是的，用这个语法ffmpeg -ss 00:00:00 -i %@ -c:v libx264 -preset ultrafast -x264-params lossless=1 %@

**Comment by YYHNobug** [comment]
http://cdn.lemmovie.com/live/774f3505-7de7-4fb0-a560-cc718f8934eb.m3u8
这个可以转mp4吗？没看懂你那个语法啊

**Comment by RideShi** [comment]
我的也是m3u8,不过我是先下载获取到ts文件格式的，俩个%@，第一个是你需要转换的h265文件（我这边时下载的h265格式的ts文件），第二个是转换之后存储的地址加格式，主要是处理h265 转换的格式是你自己定的

**Comment by RideShi** [comment]
![image](https://user-images.githubusercontent.com/15190511/60787349-1b7a3d00-a18c-11e9-97f8-4ab24bb47dc3.png)

**Comment by YYHNobug** [comment]
你们是把m3u8文件下载到本地，然后在转成mp4，在去播放，这样不很耗时吗？ 我们的资源主要是电视台的直播频道，FFMpeg玩的不是很熟

**Comment by YYHNobug** [comment]
你们是点播资源吧

**Comment by RideShi** [comment]
是的，那就更简单了啊 ，用 AVURLAsset去播放，可以直接播放的
![image](https://user-images.githubusercontent.com/15190511/60787987-1fa75a00-a18e-11e9-8c2f-f88b3679e190.png)

**Comment by RideShi** [comment]
我是需要保存本地，不然也不需要转格式那么麻烦

**Comment by YYHNobug** [comment]
问题就是用AVURLAsset播放会出现有声音没画面的情况，你用你的播放器测下这个 http://cdn.lemmovie.com/live/774f3505-7de7-4fb0-a560-cc718f8934eb.m3u8
能播不？

**Comment by RideShi** [comment]
用网页直接播你这个都没有画面的，获取的AVURLAsset也是nil

**Comment by YYHNobug** [comment]
用苹果的safari播放和微信播放都是没有画面的，用IJK播放是可以的，但我们的视频加了防盗链，IJK不支持解密，所以针对h265的看有其它方案没？（转成mp4或者编解码）

**Comment by RideShi** [comment]
你用解密后的URL试一下呢，这种情况我也不清楚

**Comment by RideShi** [comment]
FFMpeg转码应该是可以的，不需要下载  你可以搜一下FFMpeg处理m3u8的

**Comment by YYHNobug** [comment]
FFMpeg转码是直接用终端通过命令转的吗？感觉也不是这么玩的，哈哈

**Comment by RideShi** [comment]
不是的，你看看这个https://www.jianshu.com/p/70b0af4d0ec7，m3u8你要搜一下，我觉得你们URL加密过的话，还是试一下解密的比较快，我这边用解密后的URL是可以正常播放的

**Comment by YYHNobug** [comment]
嗯嗯，好的，谢谢了
